import Head from 'next/head'
import Header from '../components/Header.jsx';
import MainContent from '../components/MainContent.jsx';
import Sidebar from '../components/Sidebar.jsx';
import SmallSidebar from '../components/SmallSidebar.jsx';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Skrate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <Header/>
     <Sidebar/>
     <SmallSidebar/>
     <MainContent/>
    </div>
  )
}
